Repository chocolatey/docs, pull requests merged in 2022-09, with the labels that each got.

#549 (#548) Fix bug in license update script for C4BAE
  input/en-us/c4b-environments/azure/license-update.md
Labels: Bug, Documentation

#551 (maint) Synced file(s) with chocolatey/.github
  LICENSE
Labels: BuildAutomation

#544 (#543) Increases documentation for dependencies in Chocolatey
  input/en-us/create/package-dependencies.md
Labels: Documentation, Enhancement
